package edu.eci.cosw.proyecto.model;
// Generated 16/10/2015 07:04:08 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetallePedidoProducto generated by hbm2java
 */
@Entity
@Table(name="Detalle_Pedido_Producto"
)
public class DetallePedidoProducto  implements java.io.Serializable {


     private DetallePedidoProductoId id;
     private PedidoProducto pedidoProducto;
     private Producto producto;
     private int cantidad;

    public DetallePedidoProducto() {
    }

    public DetallePedidoProducto(DetallePedidoProductoId id, PedidoProducto pedidoProducto, Producto producto, int cantidad) {
       this.id = id;
       this.pedidoProducto = pedidoProducto;
       this.producto = producto;
       this.cantidad = cantidad;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pedidoIdpedido", column=@Column(name="Pedido_IDPEDIDO", nullable=false) ), 
        @AttributeOverride(name="productoIdProducto", column=@Column(name="Producto_idProducto", nullable=false) ) } )
    public DetallePedidoProductoId getId() {
        return this.id;
    }
    
    public void setId(DetallePedidoProductoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Pedido_IDPEDIDO", nullable=false, insertable=false, updatable=false)
    public PedidoProducto getPedidoProducto() {
        return this.pedidoProducto;
    }
    
    public void setPedidoProducto(PedidoProducto pedidoProducto) {
        this.pedidoProducto = pedidoProducto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Producto_idProducto", nullable=false, insertable=false, updatable=false)
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }

    
    @Column(name="CANTIDAD", nullable=false)
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }




}


