package edu.eci.cosw.proyecto.model;
// Generated 20/10/2015 07:04:08 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EnvioProducto generated by hbm2java
 */
@Entity
@Table(name="Envio_Producto"
)
public class EnvioProducto  implements java.io.Serializable {


     private Integer idenvio;
     private PedidoProducto pedidoProducto;
     private Date fecha;
     private Date horasalida;
     private String estado;

    public EnvioProducto() {
    }

    public EnvioProducto(PedidoProducto pedidoProducto, Date fecha, Date horasalida, String estado) {
       this.pedidoProducto = pedidoProducto;
       this.fecha = fecha;
       this.horasalida = horasalida;
       this.estado = estado;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDENVIO", unique=true, nullable=false)
    public Integer getIdenvio() {
        return this.idenvio;
    }
    
    public void setIdenvio(Integer idenvio) {
        this.idenvio = idenvio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Pedido_IDPEDIDO", nullable=false)
    public PedidoProducto getPedidoProducto() {
        return this.pedidoProducto;
    }
    
    public void setPedidoProducto(PedidoProducto pedidoProducto) {
        this.pedidoProducto = pedidoProducto;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="HORASALIDA", nullable=false, length=19)
    public Date getHorasalida() {
        return this.horasalida;
    }
    
    public void setHorasalida(Date horasalida) {
        this.horasalida = horasalida;
    }

    
    @Column(name="ESTADO", nullable=false, length=45)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


