package edu.eci.cosw.proyecto.model;
// Generated 20/10/2015 07:04:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Proveedor generated by hbm2java
 */
@Entity
@Table(name="Proveedor"
)
public class Proveedor  implements java.io.Serializable {


     private Integer idProveedor;
     private String nombre;
     private String direccion;
     private String telefono;
     private Set<Producto> productos = new HashSet<Producto>(0);
     private Set<Transporte> transportes = new HashSet<Transporte>(0);

    public Proveedor() {
    }

	
    public Proveedor(String nombre, String direccion, String telefono) {
        this.nombre = nombre;
        this.direccion = direccion;
        this.telefono = telefono;
    }
    public Proveedor(String nombre, String direccion, String telefono, Set<Producto> productos, Set<Transporte> transportes) {
       this.nombre = nombre;
       this.direccion = direccion;
       this.telefono = telefono;
       this.productos = productos;
       this.transportes = transportes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idProveedor", unique=true, nullable=false)
    public Integer getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(Integer idProveedor) {
        this.idProveedor = idProveedor;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="direccion", nullable=false, length=45)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="telefono", nullable=false, length=45)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="Producto_has_Proveedor", catalog="cosw4", joinColumns = { 
        @JoinColumn(name="Proveedor_idProveedor", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="Producto_idProducto", nullable=false, updatable=false) })
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proveedor")
    public Set<Transporte> getTransportes() {
        return this.transportes;
    }
    
    public void setTransportes(Set<Transporte> transportes) {
        this.transportes = transportes;
    }


}


