package edu.eci.cosw.persistenceexercises.simplepersistencelayer;
// Generated 20/10/2015 07:04:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Evaluacion generated by hbm2java
 */
@Entity
@Table(name="Evaluacion"
    ,catalog="cosw4"
)
public class Evaluacion  implements java.io.Serializable {


     private Integer idEvaluacion;
     private String valor;
     private String comentario;
     private Set transportes = new HashSet(0);
     private Set productos = new HashSet(0);

    public Evaluacion() {
    }

	
    public Evaluacion(String valor, String comentario) {
        this.valor = valor;
        this.comentario = comentario;
    }
    public Evaluacion(String valor, String comentario, Set transportes, Set productos) {
       this.valor = valor;
       this.comentario = comentario;
       this.transportes = transportes;
       this.productos = productos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idEvaluacion", unique=true, nullable=false)
    public Integer getIdEvaluacion() {
        return this.idEvaluacion;
    }
    
    public void setIdEvaluacion(Integer idEvaluacion) {
        this.idEvaluacion = idEvaluacion;
    }

    
    @Column(name="valor", nullable=false, length=2)
    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }

    
    @Column(name="comentario", nullable=false, length=100)
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="evaluacion")
    public Set getTransportes() {
        return this.transportes;
    }
    
    public void setTransportes(Set transportes) {
        this.transportes = transportes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="evaluacion")
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


