package edu.eci.cosw.persistenceexercises.simplepersistencelayer;
// Generated 20/10/2015 07:04:08 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PedidoProducto generated by hbm2java
 */
@Entity
@Table(name="Pedido_Producto"
)
public class PedidoProducto  implements java.io.Serializable {


     private Integer idpedido;
     private Cliente cliente;
     private Transaccion transaccion;
     private Date fecha;
     private Set<EnvioProducto> envioProductos = new HashSet<EnvioProducto>(0);
     private Set<DetallePedidoProducto> detallePedidoProductos = new HashSet<DetallePedidoProducto>(0);

    public PedidoProducto() {
    }

	
    public PedidoProducto(Cliente cliente, Transaccion transaccion, Date fecha) {
        this.cliente = cliente;
        this.transaccion = transaccion;
        this.fecha = fecha;
    }
    public PedidoProducto(Cliente cliente, Transaccion transaccion, Date fecha, Set<EnvioProducto> envioProductos, Set<DetallePedidoProducto> detallePedidoProductos) {
       this.cliente = cliente;
       this.transaccion = transaccion;
       this.fecha = fecha;
       this.envioProductos = envioProductos;
       this.detallePedidoProductos = detallePedidoProductos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDPEDIDO", unique=true, nullable=false)
    public Integer getIdpedido() {
        return this.idpedido;
    }
    
    public void setIdpedido(Integer idpedido) {
        this.idpedido = idpedido;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Cliente_IDCLIENTE", nullable=false)
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Transaccion_idTransaccion", nullable=false)
    public Transaccion getTransaccion() {
        return this.transaccion;
    }
    
    public void setTransaccion(Transaccion transaccion) {
        this.transaccion = transaccion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECHA", nullable=false, length=19)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pedidoProducto")
    public Set<EnvioProducto> getEnvioProductos() {
        return this.envioProductos;
    }
    
    public void setEnvioProductos(Set<EnvioProducto> envioProductos) {
        this.envioProductos = envioProductos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pedidoProducto")
    public Set<DetallePedidoProducto> getDetallePedidoProductos() {
        return this.detallePedidoProductos;
    }
    
    public void setDetallePedidoProductos(Set<DetallePedidoProducto> detallePedidoProductos) {
        this.detallePedidoProductos = detallePedidoProductos;
    }




}


