package edu.eci.cosw.persistenceexercises.simplepersistencelayer;
// Generated 20/10/2015 07:04:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name="Producto"
)
public class Producto  implements java.io.Serializable {


     private Integer idProducto;
     private Evaluacion evaluacion;
     private int precio;
     private String nombre;
     private String descripcion;
     private Set<DetallePedidoProducto> detallePedidoProductos = new HashSet<DetallePedidoProducto>(0);
     private Set<Proveedor> proveedors = new HashSet<Proveedor>(0);

    public Producto() {
    }

	
    public Producto(Evaluacion evaluacion, int precio, String nombre, String descripcion) {
        this.evaluacion = evaluacion;
        this.precio = precio;
        this.nombre = nombre;
        this.descripcion = descripcion;
    }
    public Producto(Evaluacion evaluacion, int precio, String nombre, String descripcion, Set<DetallePedidoProducto> detallePedidoProductos, Set<Proveedor> proveedors) {
       this.evaluacion = evaluacion;
       this.precio = precio;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.detallePedidoProductos = detallePedidoProductos;
       this.proveedors = proveedors;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idProducto", unique=true, nullable=false)
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Evaluacion_idEvaluacion", nullable=false)
    public Evaluacion getEvaluacion() {
        return this.evaluacion;
    }
    
    public void setEvaluacion(Evaluacion evaluacion) {
        this.evaluacion = evaluacion;
    }

    
    @Column(name="precio", nullable=false)
    public int getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(int precio) {
        this.precio = precio;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descripcion", nullable=false, length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="producto")
    public Set<DetallePedidoProducto> getDetallePedidoProductos() {
        return this.detallePedidoProductos;
    }
    
    public void setDetallePedidoProductos(Set<DetallePedidoProducto> detallePedidoProductos) {
        this.detallePedidoProductos = detallePedidoProductos;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="Producto_has_Proveedor", catalog="cosw4", joinColumns = { 
        @JoinColumn(name="Producto_idProducto", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="Proveedor_idProveedor", nullable=false, updatable=false) })
    public Set<Proveedor> getProveedors() {
        return this.proveedors;
    }
    
    public void setProveedors(Set<Proveedor> proveedors) {
        this.proveedors = proveedors;
    }




}


