package edu.eci.cosw.persistenceexercises.simplepersistencelayer;
// Generated 20/10/2015 07:04:08 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Transaccion generated by hbm2java
 */
@Entity
@Table(name="Transaccion"
    ,catalog="cosw4"
)
public class Transaccion  implements java.io.Serializable {


     private Integer idTransaccion;
     private boolean aprobacion;
     private Date fecha;
     private Set pedidoTransportes = new HashSet(0);
     private Set pedidoProductos = new HashSet(0);

    public Transaccion() {
    }

	
    public Transaccion(boolean aprobacion, Date fecha) {
        this.aprobacion = aprobacion;
        this.fecha = fecha;
    }
    public Transaccion(boolean aprobacion, Date fecha, Set pedidoTransportes, Set pedidoProductos) {
       this.aprobacion = aprobacion;
       this.fecha = fecha;
       this.pedidoTransportes = pedidoTransportes;
       this.pedidoProductos = pedidoProductos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idTransaccion", unique=true, nullable=false)
    public Integer getIdTransaccion() {
        return this.idTransaccion;
    }
    
    public void setIdTransaccion(Integer idTransaccion) {
        this.idTransaccion = idTransaccion;
    }

    
    @Column(name="aprobacion", nullable=false)
    public boolean isAprobacion() {
        return this.aprobacion;
    }
    
    public void setAprobacion(boolean aprobacion) {
        this.aprobacion = aprobacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Fecha", nullable=false, length=19)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="transaccion")
    public Set getPedidoTransportes() {
        return this.pedidoTransportes;
    }
    
    public void setPedidoTransportes(Set pedidoTransportes) {
        this.pedidoTransportes = pedidoTransportes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="transaccion")
    public Set getPedidoProductos() {
        return this.pedidoProductos;
    }
    
    public void setPedidoProductos(Set pedidoProductos) {
        this.pedidoProductos = pedidoProductos;
    }




}


